mini_blog/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

mini_blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

mini_blog/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :description, presence:true
  validates :title, length: {minimum:5}
  validates :description, length: {minimum:15}

#   #jeito finalizado na aula
#   before_save do
#     self.title = self.title + "Leonardo"
#   end
# end

  before_save do
    last_post_id = Post.last&.id || 0
    self.title = "#{self.title} - Leonardo's Post #{last_post_id + 1}"
  end
end


#   before_save do
#     if self.post_id.present? && Post.exists?(self.post_id)
#       idpost = Post.find(self.post_id)
#       self.title = "#{self.title} - Leonardo's Post #{idpost.id}"
#     end
#   end
# end

mini_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

mini_blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

mini_blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

mini_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

mini_blog/app/helpers/home_helper.rb
module HomeHelper
end

mini_blog/app/helpers/posts_helper.rb
module PostsHelper
end

mini_blog/app/views/home/index.html.erb
<h1>Olá, bem vindo ao meu blog</h1>
<p>Find me in app/views/home/index.html.erb</p>

<% @posts.each do |post| %>
  <%if post.description? %>
 <h2> <%= link_to post.title, post %> </h2>
    <%end %>
<% end %>

<% #criando um botão para ir até a pagina posts %>
<%= link_to "Posts", posts_path %>

mini_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

mini_blog/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

mini_blog/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

</div>

mini_blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

mini_blog/app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts do Leonardo</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>
<%= link_to "Voltar", root_path %>

mini_blog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

mini_blog/app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>